/* =============================================================================
 *  excelImport.js  —  IN-BROWSER EXCEL (.xlsx) IMPORTER  (no libraries)
 * =============================================================================
 *
 *  Reads a `.xlsx` workbook entirely ON THIS DEVICE — the file is NEVER uploaded.
 *  An `.xlsx` is just a ZIP of XML files, so this module:
 *    1) reads the ZIP entries (central directory + local headers),
 *    2) inflates each with the browser's DecompressionStream('deflate-raw'),
 *    3) parses xl/workbook.xml (+ its .rels), xl/worksheets/sheetN.xml, and
 *       xl/sharedStrings.xml with plain string/regex scanning,
 *    4) reads each property tab's label (col B) / value (col C) pairs and maps
 *       them onto the scenario schema (see fieldSchema.js), defaulting anything
 *       the template does not cover.
 *
 *  It only READS the workbook. After import the user reviews the numbers and
 *  hits "Save scenario" to keep the JSON on their device.
 *
 *  Matching template: `Property Data Collection Template.xlsx` (repo root),
 *  generated by tools/buildExcelTemplate.js from these same schema labels.
 * ---------------------------------------------------------------------------*/

window.FP = window.FP || {};

FP.excelImport = (function () {
  'use strict';

  // ---- little binary helpers -------------------------------------------------
  function u16(b, o) { return b[o] | (b[o + 1] << 8); }
  function u32(b, o) { return (b[o] | (b[o + 1] << 8) | (b[o + 2] << 16) | (b[o + 3] << 24)) >>> 0; }
  function textDecode(u8) { return new TextDecoder('utf-8').decode(u8); }

  // Inflate a raw DEFLATE stream (ZIP method 8) using the browser's built-in
  // DecompressionStream. Returns a Uint8Array. (Async.)
  function inflateRaw(bytes) {
    var ds = new DecompressionStream('deflate-raw');
    var stream = new Blob([bytes]).stream().pipeThrough(ds);
    return new Response(stream).arrayBuffer().then(function (ab) { return new Uint8Array(ab); });
  }

  // ---- ZIP reader ------------------------------------------------------------
  // Returns a promise for { filename: Uint8Array } of every entry.
  function readZip(arrayBuffer) {
    var b = new Uint8Array(arrayBuffer);

    // Find the End Of Central Directory record (signature 0x06054b50), scanning
    // back from the end (there may be a trailing comment, so we search).
    var eocd = -1;
    for (var i = b.length - 22; i >= 0; i--) { if (u32(b, i) === 0x06054b50) { eocd = i; break; } }
    if (eocd < 0) throw new Error('That does not look like an .xlsx file (no ZIP end record).');

    var count = u16(b, eocd + 10);
    var cdOffset = u32(b, eocd + 16);

    var entries = [], p = cdOffset;
    for (var n = 0; n < count; n++) {
      if (u32(b, p) !== 0x02014b50) break; // central directory header signature
      var method = u16(b, p + 10);
      var compSize = u32(b, p + 20);
      var nameLen = u16(b, p + 28);
      var extraLen = u16(b, p + 30);
      var commentLen = u16(b, p + 32);
      var localOff = u32(b, p + 42);
      var name = textDecode(b.subarray(p + 46, p + 46 + nameLen));
      entries.push({ name: name, method: method, compSize: compSize, localOff: localOff });
      p += 46 + nameLen + extraLen + commentLen;
    }

    // Decompress each entry from its local header (which repeats name/extra lens).
    var out = {};
    var chain = Promise.resolve();
    entries.forEach(function (e) {
      chain = chain.then(function () {
        var lh = e.localOff;
        if (u32(b, lh) !== 0x04034b50) throw new Error('Corrupt ZIP (bad local header for ' + e.name + ').');
        var lNameLen = u16(b, lh + 26);
        var lExtraLen = u16(b, lh + 28);
        var dataStart = lh + 30 + lNameLen + lExtraLen;
        var comp = b.subarray(dataStart, dataStart + e.compSize);
        if (e.method === 0) { out[e.name] = comp; return; }            // stored
        if (e.method === 8) { return inflateRaw(comp).then(function (u) { out[e.name] = u; }); } // deflate
        throw new Error('Unsupported compression method ' + e.method + ' in ' + e.name + '.');
      });
    });
    return chain.then(function () { return out; });
  }

  // ---- XML scanning (no DOMParser, so it also runs headless in Node tests) ----
  function unescapeXml(s) {
    return String(s)
      .replace(/&lt;/g, '<').replace(/&gt;/g, '>')
      .replace(/&quot;/g, '"').replace(/&apos;/g, "'")
      .replace(/&#x([0-9a-fA-F]+);/g, function (_, h) { return String.fromCharCode(parseInt(h, 16)); })
      .replace(/&#(\d+);/g, function (_, d) { return String.fromCharCode(+d); })
      .replace(/&amp;/g, '&'); // ampersand LAST so it doesn't double-decode
  }

  function parseSharedStrings(xml) {
    var out = [];
    xml.replace(/<si\b[^>]*>([\s\S]*?)<\/si>/g, function (_, inner) {
      var t = '';
      inner.replace(/<t\b[^>]*>([\s\S]*?)<\/t>/g, function (__, txt) { t += txt; return ''; });
      out.push(unescapeXml(t));
      return '';
    });
    return out;
  }

  // Returns { "B2": value, ... } for one worksheet. Values are strings or numbers.
  function parseSheet(xml, shared) {
    var cells = {};
    // Drop self-closing EMPTY cells first (<c r="B2"/>). If left in, the open/close
    // matcher below would treat them as open tags and greedily swallow the next
    // real cell as their "inner", corrupting the parse.
    xml = xml.replace(/<c\b[^>]*\/>/g, '');
    xml.replace(/<c\b([^>]*)>([\s\S]*?)<\/c>/g, function (_, attrs, inner) {
      var refM = /\br="([A-Z]+\d+)"/.exec(attrs);
      if (!refM) return '';
      var ref = refM[1];
      var typeM = /\bt="([^"]+)"/.exec(attrs);
      var type = typeM ? typeM[1] : 'n';
      var val = null, m;
      if (type === 's') {                       // shared string (index in <v>)
        m = /<v>([\s\S]*?)<\/v>/.exec(inner);
        if (m) val = shared[+m[1]];
      } else if (type === 'inlineStr') {         // inline string
        m = /<t\b[^>]*>([\s\S]*?)<\/t>/.exec(inner);
        if (m) val = unescapeXml(m[1]);
      } else if (type === 'str') {               // formula string result
        m = /<v>([\s\S]*?)<\/v>/.exec(inner);
        if (m) val = unescapeXml(m[1]);
      } else if (type === 'b') {                 // boolean
        m = /<v>([\s\S]*?)<\/v>/.exec(inner);
        if (m) val = (m[1] === '1');
      } else {                                   // number (default)
        m = /<v>([\s\S]*?)<\/v>/.exec(inner);
        if (m) val = parseFloat(m[1]);
      }
      cells[ref] = val;
      return '';
    });
    return cells;
  }

  function colRow(ref) { var m = /^([A-Z]+)(\d+)$/.exec(ref); return m ? { col: m[1], row: +m[2] } : null; }

  // Map r:id -> worksheet part path, in document (sheet) order.
  function parseWorkbook(files) {
    var wbXml = textDecode(files['xl/workbook.xml'] || new Uint8Array());
    var relsXml = files['xl/_rels/workbook.xml.rels'] ? textDecode(files['xl/_rels/workbook.xml.rels']) : '';
    var rel = {};
    relsXml.replace(/<Relationship\b([^>]*)\/?>(?:<\/Relationship>)?/g, function (_, a) {
      var id = /Id="([^"]+)"/.exec(a), tgt = /Target="([^"]+)"/.exec(a);
      if (id && tgt) rel[id[1]] = tgt[1];
      return '';
    });
    var sheets = [];
    wbXml.replace(/<sheet\b([^>]*)\/?>(?:<\/sheet>)?/g, function (_, a) {
      var nameM = /name="([^"]+)"/.exec(a);
      var ridM = /r:id="([^"]+)"/.exec(a) || /[: ]id="([^"]+)"/.exec(a);
      var target = ridM ? rel[ridM[1]] : null;
      var file = null;
      if (target) file = (target.charAt(0) === '/') ? target.slice(1) : ('xl/' + target.replace(/^\.\//, ''));
      sheets.push({ name: nameM ? unescapeXml(nameM[1]) : ('Sheet' + (sheets.length + 1)), file: file });
      return '';
    });
    return sheets;
  }

  // ---- label -> scenario key mapping ----------------------------------------
  // Normalize a label so small human differences (case, units, punctuation) match.
  function normalize(s) { return String(s).toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim(); }

  var PERCENT_KEYS = { annualDepreciationRate: 1, capitalReservePctOfValue: 1, vacancyAllowancePct: 1,
    mortgageRate: 1, appreciationRate: 1, sellingCostsPct: 1, transferTaxRate: 1,
    'seasonal.peakOccupancyPct': 1, 'seasonal.offSeasonOccupancyPct': 1 };
  var BOOL_KEYS = { holdIndefinitely: 1, section121Eligible: 1, 'seasonal.enabled': 1 };
  var YEAR_KEYS = { conversionYear: 1, plannedSaleYear: 1 };
  var DATE_KEYS = { purchaseDate: 1, placedInServiceDate: 1, mortgageOriginationDate: 1 };
  var TEXT_KEYS = { name: 1, state: 1, ownershipEntity: 1 };

  // Build the label map from the SAME schema the template is generated from, plus
  // a few aliases a human might reasonably type.
  function buildLabelMap() {
    var map = {};
    function add(label, key) { map[normalize(label)] = key; }
    (FP.propertyFieldSchema || []).forEach(function (f) { add(f.label, f.key); });
    (FP.seasonalFieldSchema || []).forEach(function (f) { add(f.label, 'seasonal.' + f.key); });
    // Aliases (robustness against slightly different wording).
    add('Section 121 eligible', 'section121Eligible');
    add('121 eligible', 'section121Eligible');
    add('Land allocation', 'landAllocation');
    add('Housekeeping turnover', 'housekeepingTurnover');
    add('Seasonal enabled', 'seasonal.enabled');
    return map;
  }

  function excelSerialToISO(n) {
    // Excel's day 25569 is 1970-01-01 (the Unix epoch), 1 day = 86,400,000 ms.
    var d = new Date(Math.round((n - 25569) * 86400000));
    return isNaN(d.getTime()) ? null : d.toISOString().slice(0, 10);
  }

  // Coerce a raw cell value to the type the given key expects. Returns undefined
  // to mean "leave the default" (blank cell).
  function coerce(key, raw) {
    if (raw === null || raw === undefined || raw === '') return undefined;
    if (BOOL_KEYS[key]) {
      if (typeof raw === 'boolean') return raw;
      var s = String(raw).trim().toLowerCase();
      return s === 'true' || s === 'yes' || s === 'y' || s === '1' || s === 'x';
    }
    if (TEXT_KEYS[key]) return String(raw).trim();
    if (YEAR_KEYS[key]) {
      var sy = String(raw).trim().toLowerCase();
      if (sy === '' || sy === 'hold') return 'hold';
      var y = parseInt(raw, 10); return isNaN(y) ? 'hold' : y;
    }
    if (DATE_KEYS[key]) {
      if (typeof raw === 'number') return excelSerialToISO(raw);
      return String(raw).trim();
    }
    var n = (typeof raw === 'number') ? raw : parseFloat(String(raw).replace(/[$,%\s]/g, ''));
    if (isNaN(n)) return undefined;
    // Percent fields are stored as DECIMALS (0.05 = 5%), matching how Excel stores
    // a percent-formatted cell. Safety net: a clearly-whole-number entry (> 1.5,
    // e.g. someone typed "6" meaning 6%) is divided by 100.
    if (PERCENT_KEYS[key] && Math.abs(n) > 1.5) n = n / 100;
    return n;
  }

  function setKey(obj, key, val) {
    if (val === undefined) return;
    if (key.indexOf('.') >= 0) { var pr = key.split('.'); (obj[pr[0]] = obj[pr[0]] || {})[pr[1]] = val; }
    else obj[key] = val;
  }

  // A property with every field at a safe default; parsed cells overlay this.
  function blankProperty() {
    return {
      id: '', name: '', state: 'CA', ownershipEntity: 'Individual', entityStockBasis: 0, isPlaceholder: false,
      purchasePrice: 0, purchaseDate: null, landAllocation: 0, capitalImprovements: 0,
      accumulatedDepreciation: 0, annualDepreciationRate: 0, placedInServiceDate: null, suspendedPassiveLosses: 0,
      conversionYear: 'hold', fmvAtConversion: 0, prop13AssessedValue: 0,
      grossRentalRevenue: 0, marketValue: 0, assessedValue: 0, propertyTax: 0, insurance: 0, hoa: 0,
      ownerPaidUtilities: 0, managementFees: 0, housekeepingTurnover: 0, routineMaintenance: 0,
      capitalReserve: 0, capitalReservePctOfValue: 0, vacancyAllowancePct: 0, nonResidentFilingCost: 0,
      mortgageBalance: 0, mortgageRate: 0, mortgageTermYears: 30, mortgageOriginationDate: null,
      holdIndefinitely: false, appreciationRate: 0, sellingCostsPct: 0.06, plannedSaleYear: 'hold',
      section121Eligible: false, transferTaxRate: 0,
      seasonal: { enabled: false, peakNightlyRate: 0, peakMonths: 0, offSeasonNightlyRate: 0,
                  peakOccupancyPct: 0, offSeasonOccupancyPct: 0 }
    };
  }

  // Turn one worksheet's cells into a property object (or null if unrecognized).
  function sheetToProperty(cells, sheetName, labelMap) {
    var p = blankProperty();
    p.id = 'import-' + normalize(sheetName).replace(/\s+/g, '-').slice(0, 24) + '-' + Math.random().toString(36).slice(2, 6);
    p.name = sheetName;

    // Group cells by row so we can read label (col B, fallback A) + value (col C,
    // fallback B).
    var byRow = {};
    Object.keys(cells).forEach(function (ref) {
      var cr = colRow(ref); if (!cr) return;
      (byRow[cr.row] = byRow[cr.row] || {})[cr.col] = cells[ref];
    });

    var found = 0, legacyOcc;
    Object.keys(byRow).forEach(function (rn) {
      var row = byRow[rn];
      var labelInB = (row.B !== undefined && row.B !== null && row.B !== '');
      var label = labelInB ? row.B : row.A;
      var value = labelInB ? row.C : row.B;
      if (label === undefined || label === null || label === '') return;
      var norm = normalize(label);
      if (norm === 'occupancy') { legacyOcc = value; return; } // B4 migration (single occupancy)
      var key = labelMap[norm];
      if (!key) return;
      var v = coerce(key, value);
      if (v !== undefined) { setKey(p, key, v); found++; }
    });

    if (legacyOcc !== undefined) {
      var lv = coerce('seasonal.peakOccupancyPct', legacyOcc);
      if (lv !== undefined) { p.seasonal.peakOccupancyPct = lv; p.seasonal.offSeasonOccupancyPct = lv; found++; }
    }
    return found > 0 ? p : null;
  }

  // Tabs that are NOT property data.
  var SKIP_SHEETS = { 'readme': 1, 'read me': 1, 'instructions': 1, 'example format': 1, 'example': 1,
    'portfolio summary': 1, 'summary': 1, 'settings': 1 };

  // Full pipeline: an ArrayBuffer of an .xlsx -> a scenario object. (Async.)
  function scenarioFromArrayBuffer(arrayBuffer) {
    return readZip(arrayBuffer).then(function (files) {
      var sheets = parseWorkbook(files);
      var shared = files['xl/sharedStrings.xml'] ? parseSharedStrings(textDecode(files['xl/sharedStrings.xml'])) : [];
      var labelMap = buildLabelMap();

      var props = [];
      sheets.forEach(function (sh) {
        if (!sh.file || !files[sh.file]) return;
        if (SKIP_SHEETS[normalize(sh.name)]) return;
        var cells = parseSheet(textDecode(files[sh.file]), shared);
        var p = sheetToProperty(cells, sh.name, labelMap);
        if (p) props.push(p);
      });
      if (props.length === 0) {
        throw new Error('No property tabs were recognized. Make sure each property is on its own tab using the template labels.');
      }

      // Scenario-level settings aren't in the per-property tabs, so default them.
      var scenario = FP.makeDefaultScenario();
      scenario.label = 'Imported from Excel';
      scenario.isPlaceholder = false;
      scenario.properties = props;
      return scenario;
    });
  }

  // ---- UI: an "Import from Excel" control -----------------------------------
  function mount(container, onImport) {
    if (!container) return;
    container.innerHTML = '';

    var intro = document.createElement('p');
    intro.className = 'fp-muted';
    intro.textContent = 'Load an Excel workbook (.xlsx) that uses the template layout — one tab per property, '
      + 'labels in column B and values in column C. The file is read only on this device; nothing is uploaded. '
      + 'After importing, review the numbers, then use "Save scenario (JSON)" above to keep them.';

    var btn = document.createElement('label');
    btn.className = 'fp-btn fp-btn-file';
    btn.appendChild(document.createTextNode('📄 Import from Excel (.xlsx)'));
    var input = document.createElement('input');
    input.type = 'file';
    input.accept = '.xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
    input.hidden = true;
    btn.appendChild(input);

    var status = document.createElement('p');
    status.className = 'fp-muted';
    status.style.marginTop = '8px';

    input.addEventListener('change', function (e) {
      var file = e.target.files && e.target.files[0];
      e.target.value = '';
      if (!file) return;
      status.className = 'fp-muted';
      status.textContent = 'Reading ' + file.name + '…';
      file.arrayBuffer()
        .then(scenarioFromArrayBuffer)
        .then(function (sc) {
          status.className = 'fp-muted';
          status.textContent = 'Imported ' + sc.properties.length + ' propert'
            + (sc.properties.length === 1 ? 'y' : 'ies') + ' from ' + file.name
            + '. Review the numbers, then Save scenario to keep them.';
          if (typeof onImport === 'function') onImport(sc);
        })
        .catch(function (err) {
          status.className = 'fp-warning';
          status.textContent = 'Could not import that file: ' + err.message;
        });
    });

    container.appendChild(intro);
    container.appendChild(btn);
    container.appendChild(status);
  }

  return {
    mount: mount,
    scenarioFromArrayBuffer: scenarioFromArrayBuffer,
    // exposed for tests:
    _readZip: readZip, _parseSheet: parseSheet, _parseSharedStrings: parseSharedStrings,
    _parseWorkbook: parseWorkbook, _buildLabelMap: buildLabelMap, _normalize: normalize,
    _sheetToProperty: sheetToProperty, _coerce: coerce
  };
})();
